name: horse-riding-registration-dev

services:
  database:
    image: postgres:15
    container_name: horse-riding-registration-dev__database
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
