import type { Metadata } from "next";
import "./globals.css";
import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from '@mantine/core';
import { theme } from './theme';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
			<head>
				<ColorSchemeScript defaultColorScheme="dark" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
			</head>
      <body
        className={`antialiased`}
      >
        <MantineProvider theme={theme} defaultColorScheme="dark" withGlobalClasses>
					{children}
				</MantineProvider>
      </body>
    </html>
  );
}
